services:
  - type: web
    name: phishguard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://phishing-detector-two-nu.vercel.app" # Your Vercel frontend URL
      - key: PYTHON_VERSION
        value: 3.11.0
